FROM node:8 as react-frontend-compile-builder

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY . /app

RUN npm run build

FROM nginx

COPY --from=react-frontend-compile-builder /app/build/ /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80